[server]
headless = false
address = "localhost"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#0284c7"
